name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@main
      - name: Create .env
        run: |
          echo 'DB_NAME=wordpress' >> .env
          echo 'DB_USER=wpuser' >> .env
          echo 'DB_PASSWORD=password' >> .env
          echo 'DB_ROOT_PASSWORD=root_password' >> .env


      - name: Build Docker
        run: docker compose up --build -d 
