name: CI/CD for WordPress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wpuser
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: root_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      wordpress:
        image: wordpress:latest
        ports:
          - 8080:80
        env:
          WORDPRESS_DB_HOST: mysql
          WORDPRESS_DB_USER: wpuser
          WORDPRESS_DB_PASSWORD: password
          WORDPRESS_DB_NAME: wordpress
        options: >-
          --health-cmd="curl -f http://localhost || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      nginx:
        image: nginx:1.27.0
        ports:
          - 8081:80
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
          - ./src:/var/www/html
        options: >-
          --health-cmd="curl -f http://localhost || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker images
      run: docker-compose -f docker-compose.yml up -d

    - name: Run tests
      run: |
        # Chạy các lệnh kiểm tra, ví dụ: kiểm tra kết nối đến WordPress và Nginx
        curl -I http://localhost:8081
        curl -I http://localhost:8080
